name: monstercatplayer
description: Monstercat player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.8+8

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  http: ^0.13.3
  xml: ^5.0.0
  intl: ^0.18.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.12
  restart_app: ^1.1.2
  device_info: ^2.0.3
  transparent_image: ^2.0.1
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.3.1
  fluttertoast: ^8.0.8
  flutter_otp_text_field: ^1.1.0+2
  clipboard: ^0.1.3
  package_info_plus: ^4.0.2
  share_plus: ^7.0.2
  pubspec_yaml: ^3.1.0
  in_app_review: ^2.0.6
  flutter_staggered_grid_view: ^0.4.0
  flutter_markdown: ^0.6.17+1
  system_theme: ^2.3.1
  just_audio: ^0.9.34
  provider: ^6.0.5
  uni_links: ^0.5.1
  permission_handler: ^11.0.1



  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/puzzak_av.jpg
    - assets/darkplayer_av.png
    - assets/icons/brand-figma.png
    - assets/icons/github-alt.png
    - assets/icons/telegram-alt.png
    - assets/icons/twitter-alt.png
    - pubspec.yaml

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
    - family: Flow
      fonts:
        - asset: assets/fonts/Flow.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
